FROM node:20-alpine
WORKDIR /app
COPY . .

ARG ARG_API_URL 
ENV REACT_APP_API_URL=${ARG_API_URL}

ARG ARG_HTTP_PORT=3000
ARG ARG_HTTPS_PORT=3001
ENV LISTENING_HTTP_PORT=${ARG_HTTP_PORT}
ENV LISTENING_HTTPS_PORT=${ARG_HTTPS_PORT}

RUN npm install

RUN npm run env

EXPOSE ${ARG_HTTP_PORT}

CMD npm run start:prod
